version: '3'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=quero35Quero
      - N8N_PORT=5678
      - TZ=America/New_York
      - N8N_EDITOR_BASE_URL=https://auto.jobfishing.us
      - WEBHOOK_URL=https://auto.jobfishing.us
      - N8N_HOST=0.0.0.0
      - N8N_PROTOCOL=https
      - N8N_PATH=/
    volumes:
      - ./data:/home/node/.n8n
